-- PR1: Idle Cost Report (daily, credits-only)
-- View(s):
--   1) V_WAREHOUSE_IDLE_CREDITS_DAILY
--   2) V_WAREHOUSE_IDLE_TOP_OFFENDERS_7D (optional helper)
--
-- Data source:
--   SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY
--
-- Notes:
-- - ACCOUNT_USAGE has documented latency (~3h). This is intended for daily reporting.
-- - We intentionally avoid $ mapping in PR1 (contract price variability).
-- - We compute idle credits as (compute credits) - (credits attributed to compute queries).
-- - We exclude the current date by default to avoid partial-day skew.

CREATE OR REPLACE VIEW V_WAREHOUSE_IDLE_CREDITS_DAILY AS
WITH daily AS (
  SELECT
    wmh.WAREHOUSE_NAME,
    DATE_TRUNC('day', wmh.START_TIME)::DATE AS USAGE_DATE,

    /* Core credit measures */
    SUM(wmh.CREDITS_USED_COMPUTE)                       AS TOTAL_COMPUTE_CREDITS,
    SUM(wmh.CREDITS_ATTRIBUTED_COMPUTE_QUERIES)         AS QUERY_ATTRIBUTED_COMPUTE_CREDITS,

    /* Derived "waste" */
    (SUM(wmh.CREDITS_USED_COMPUTE) - SUM(wmh.CREDITS_ATTRIBUTED_COMPUTE_QUERIES)) AS IDLE_COMPUTE_CREDITS,

    /* Ratio */
    ROUND(
      100 * (SUM(wmh.CREDITS_USED_COMPUTE) - SUM(wmh.CREDITS_ATTRIBUTED_COMPUTE_QUERIES))
        / NULLIF(SUM(wmh.CREDITS_USED_COMPUTE), 0),
      2
    ) AS IDLE_PCT
  FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY wmh
  WHERE 1=1
    AND wmh.START_TIME >= DATEADD('day', -60, CURRENT_DATE())
    AND wmh.END_TIME < CURRENT_DATE()  -- exclude partial current day
  GROUP BY 1, 2
)
SELECT
  WAREHOUSE_NAME,
  USAGE_DATE,
  TOTAL_COMPUTE_CREDITS,
  QUERY_ATTRIBUTED_COMPUTE_CREDITS,
  IDLE_COMPUTE_CREDITS,
  IDLE_PCT
FROM daily
WHERE TOTAL_COMPUTE_CREDITS IS NOT NULL;


CREATE OR REPLACE VIEW V_WAREHOUSE_IDLE_TOP_OFFENDERS_7D AS
WITH last_7d AS (
  SELECT
    WAREHOUSE_NAME,
    SUM(TOTAL_COMPUTE_CREDITS)               AS TOTAL_COMPUTE_CREDITS_7D,
    SUM(QUERY_ATTRIBUTED_COMPUTE_CREDITS)    AS QUERY_ATTRIBUTED_COMPUTE_CREDITS_7D,
    SUM(IDLE_COMPUTE_CREDITS)                AS IDLE_COMPUTE_CREDITS_7D,
    ROUND(100 * SUM(IDLE_COMPUTE_CREDITS) / NULLIF(SUM(TOTAL_COMPUTE_CREDITS), 0), 2) AS IDLE_PCT_7D
  FROM V_WAREHOUSE_IDLE_CREDITS_DAILY
  WHERE USAGE_DATE >= DATEADD('day', -7, CURRENT_DATE())
  GROUP BY 1
)
SELECT
  WAREHOUSE_NAME,
  TOTAL_COMPUTE_CREDITS_7D,
  QUERY_ATTRIBUTED_COMPUTE_CREDITS_7D,
  IDLE_COMPUTE_CREDITS_7D,
  IDLE_PCT_7D,
  DENSE_RANK() OVER (ORDER BY IDLE_COMPUTE_CREDITS_7D DESC) AS IDLE_CREDITS_RANK_7D
FROM last_7d
WHERE TOTAL_COMPUTE_CREDITS_7D > 0
ORDER BY IDLE_COMPUTE_CREDITS_7D DESC;
